### ISSUE TITLE
My account is lost after shutdown

### ISSUE THREAD

**Issue by dustinsharp** [3axap4eHko/OWA-Notifier#93] opened 2016-05-13 20:50 UTC
Whenever I restart my machine and open up Chrome again, the notifier has forgotten my account completely. I have to sign in every time.

**Comment by DesireeZach** [comment] 2016-05-14 13:34
Same problehere.

**Comment by grit96** [comment] 2016-05-14 15:06
Duplicate of #91

**Closed** 2016-05-14 22:55 UTC
