### ISSUE TITLE
Wrong Information

### ISSUE THREAD

**Issue by rochapablo** [3axap4eHko/OWA-Notifier#51] opened 2015-08-21 11:23 UTC
The extension are informing that I have 10 emails (for example) but It doesn't. All the emails have already been read.

**Comment by Thejode** [comment] 2015-08-21 11:46
Also having the same issue. Also the notifier keeps popping up saying I have 1 unread email, and repeats about 10 times in a row even though, I have no unread emails. I've had to turn the sound off so my colleagues don't get annoyed.

**Comment by tonytcb** [comment] 2015-08-21 12:11
And, the extension is continually notifying that it has been updated to version 3.

**Comment by arshcaria** [comment] 2015-08-21 12:45
same here

**Comment by dwolfram** [comment] 2015-08-21 15:29
Basically it keeps on notifying about the same emails until I close or click on the popup even if I've already read those emails.

**Comment by 3axap4eHko** [comment] 2015-08-23 14:17
I test this on different servers and this happens due to server cache and slow updates of changes mail server base

**Comment by arshcaria** [comment] 2015-08-24 12:20
But the extension icon does not show unread number anymore while the notification still pops up. Is it really caused by the mail server side?

**Comment by dwolfram** [comment] 2015-08-24 12:30
Indeed it doesn't look like a server issue, as I mentioned earlier the popup keeps coming up forever, until I click on it or close it.
My understanding is that the popup shouldn't come up more than once on the same message regardless of the server state or whether the message is read or not.

**Comment by 3axap4eHko** [comment] 2015-08-24 12:32
Why you don't click close?

**Comment by arshcaria** [comment] 2015-08-24 12:34
lol, that's a good question.
Sometimes users like us are too lazy to move the mouse to the corner~ ^_^

**Comment by rochapablo** [comment] 2015-08-24 12:34
It's not about that! The problem is that we always get the same message all day long, over and over. And if the issue was the server, why does that problem had never happened on the previous version?

**Comment by dwolfram** [comment] 2015-08-24 12:37
I receive hundreds of emails a day, it would be very tedious and distracting clicking on close every time I receive an email

**Comment by rochapablo** [comment] 2015-08-24 12:39
@dwolfram good point!

**Comment by 3axap4eHko** [comment] 2015-08-24 12:39
Let it be fingers workout =)

**Comment by 3axap4eHko** [comment] 2015-08-24 20:29
Fixed in 3.0.2.1 by adding popup close mode option

**Closed by 3axap4eHko** 2015-08-24 20:29 UTC
